global:
  topic_prefix: "exp_ysp/"
  service_names:
    sim_reset: "sim_reset"
  topic_names:
    joints_state: "joints_state"
    imu: "imu_data"
    touch_sensor: "touch_sensor"
    odom: "odom"
    estimated_states: "estimated_states"
    actuators_cmds: "actuators_cmds"
    mode_schedule: "mode_schedule"
    trajectories: "trajectories"

ocs2:
  package: "ocs2_legged_robot"
  reference_file: "/config/command/reference.info"
  task_file: "/config/mpc/task.info"

model:
  name: "a1"
  package: "asserts"
  urdf: "/a1/a1_0.urdf"
  xml: "/a1/a1_0.xml"
  base_name: "trunk"
  foot_names: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"]
  actuated_joints_name:
    [
      "FL_hip_joint",
      "FL_thigh_joint",
      "FL_calf_joint",
      "FR_hip_joint",
      "FR_thigh_joint",
      "FR_calf_joint",
      "RL_hip_joint",
      "RL_thigh_joint",
      "RL_calf_joint",
      "RR_hip_joint",
      "RR_thigh_joint",
      "RR_calf_joint",
    ]
  default:
    joint_pos:
      [
        0.0,
        0.688524,
        -1.42573,
        -0.0,
        0.688524,
        -1.42573,
        0.0,
        0.688524,
        -1.42573,
        -0.0,
        0.688524,
        -1.42573,
      ]
    base_pos: [0, 0, 0.32]
    base_quat: [1, 0, 0, 0]

gait:
  list: ["stance", "trot", "static_walk", "pawup"]

  stance:
    modeSequence: ["STANCE"]
    switchingTimes: [0.0, 0.5]

  trot:
    modeSequence: ["LF_RH", "RF_LH"]
    switchingTimes: [0.0, 0.3, 0.6]

  static_walk:
    modeSequence: ["LF_RF_RH", "RF_LH_RH", "LF_RF_LH", "LF_LH_RH"]
    switchingTimes: [0.0, 0.4, 0.8, 1.2, 1.6]
  
  pawup:
    modeSequence: ["RF_LH"]
    switchingTimes: [0.0, 2.0]

  topic_prefix: "simulation/"
  topic_names:
    mode_schedule: "mode_schedule"
  frequency: 500.0

simulation:
  frequency: # Hz
    joints_state: 500.0
    imu: 400.0
    touch_sensor: 500.0
    odom: 30.0
    drop_old_message: 10.0

estimation:
  dt: 0.002
  use_odom: false
  hardware: false

controller:
  frequency: 500.0
  use_vector_field: true
<<<<<<< HEAD
  log_dir: "/home/clear/workspace/VF-TSC/exp/ocs2_pro"
=======
>>>>>>> 77dc56d93f6ad7c572b7e85c1990f7f32b525a42

generation:
  frequency: 50.0
