global:
  topic_prefix: "simulation/"
  service_names:
    sim_reset: "sim_reset"
  topic_names:
    joints_state: "joints_state"
    imu: "imu_data"
    touch_sensor: "touch_sensor"
    odom: "odom"
    estimated_states: "estimated_states"
    actuators_cmds: "actuators_cmds"
    mode_schedule: "mode_schedule"
    trajectories: "trajectories"

model:
  name: "aliengo"
  package: "asserts"
  urdf: "/aliengo/aliengo.urdf"
  xml: "/aliengo/aliengo.xml"
  base_name: "trunk"
  foot_names: ["fl_foot", "fr_foot", "rl_foot", "rr_foot"]
  actuated_joints_name:
    [
      "FL_hip_joint",
      "FL_thigh_joint",
      "FL_calf_joint",
      "FR_hip_joint",
      "FR_thigh_joint",
      "FR_calf_joint",
      "RL_hip_joint",
      "RL_thigh_joint",
      "RL_calf_joint",
      "RR_hip_joint",
      "RR_thigh_joint",
      "RR_calf_joint",
    ]

gait:
  list: ["stance", "trot", "static_walk"]

  stance:
    modeSequence: ["STANCE"]
    switchingTimes: [0.0, 0.5]

  trot:
    modeSequence: ["LF_RH", "RF_LH"]
    switchingTimes: [0.0, 0.3, 0.6]
  
  static_walk:
    modeSequence: ["LF_RF_RH", "RF_LH_RH", "LF_RF_LH", "LF_LH_RH"]
    switchingTimes: [0.0, 0.4, 0.8, 1.2, 1.6]

  topic_prefix: "simulation/"
  topic_names:
    mode_schedule: "mode_schedule"
  frequency: 500.0

simulation:
  frequency: # Hz
    joints_state: 1000.0
    imu: 400.0
    touch_sensor: 500.0
    odom: 30.0
    drop_old_message: 10.0

estimation:
  dt: 0.002
  use_odom: false

controller:
  frequency: 500.0

generation:
  frequency: 100.0
